/*
 * The 21 levels of the original game. Map legend (see engine.js):
 *   '#' floor   'O' safe zone   'B' block   '@' block on a safe zone   '.' hole
 *
 * `solution` is an optimal solution, one "row,col DIR" move per entry (move the block at row,col
 * in direction U/D/L/R). Par is its length.
 *
 * Maps and solutions come from the original game's level data (safe-zone-levels.json), and each
 * level's block colour from its starting screenshot. Levels 1-19 are the originals; 20 and 21 were
 * made in 2026 to replace the old 20 and 21, which were accidental copies of level 18.
 */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.SAFE_ZONE_LEVELS = factory();
})(typeof self !== 'undefined' ? self : this, function () {
  'use strict';
  return [
    { // 1
      color: 'yellow',
      map: ['.O.',
            '###',
            '###',
            '.B.'],
      solution: ['3,1 U'],
    },
    { // 2
      color: 'orange',
      map: ['#O#',
            '###',
            'B#.'],
      solution: ['2,0 R', '2,1 U'],
    },
    { // 3
      color: 'green',
      map: ['.#O',
            '##.',
            'B#.'],
      solution: ['2,0 U', '1,0 R', '1,1 U', '0,1 R'],
    },
    { // 4
      color: 'purple',
      map: ['#O.',
            'B#B',
            '#O.'],
      solution: ['1,2 L', '1,0 U', '0,0 R', '1,1 D'],
    },
    { // 5
      color: 'yellow',
      map: ['.B#.',
            '#O##',
            '####',
            'B..#'],
      solution: ['0,1 D', '2,1 R', '2,3 U', '3,0 U', '1,3 L'],
    },
    { // 6
      color: 'yellow',
      map: ['B..###',
            '##OO#B',
            '##B###',
            '#O####'],
      solution: ['0,0 D', '2,2 D', '3,0 R', '3,2 U', '1,5 L'],
    },
    { // 7
      color: 'yellow',
      map: ['###O',
            '#O.#',
            '###B',
            '##B#'],
      solution: ['2,3 L', '2,0 U', '0,0 R', '1,0 R'],
    },
    { // 8
      color: 'green',
      map: ['B.##',
            '##O#',
            '#O.#',
            '###B'],
      solution: ['3,3 L', '0,0 D', '2,0 R', '3,0 R', '3,3 U', '0,3 L', '0,2 D'],
    },
    { // 9
      color: 'green',
      map: ['.###.',
            '##.##',
            'BO#OB',
            '##.##',
            '.#B#.'],
      solution: ['2,0 U', '1,0 R', '2,4 D', '3,4 L', '4,2 L', '4,1 U', '1,1 U', '0,1 R', '0,3 D'],
    },
    { // 10
      color: 'yellow',
      map: ['#O###O#',
            '###.###',
            '##BB###',
            'B#...#B',
            '#######',
            'O#...#O'],
      solution: ['2,2 L', '2,3 L', '2,0 U', '3,0 D', '3,6 U', '0,0 R', '0,6 D', '2,1 U'],
    },
    { // 11
      color: 'yellow',
      map: ['.O.#.O.',
            '#######',
            '####B##',
            '###.###',
            '##B.###',
            '####B##'],
      solution: ['2,4 L', '2,0 D', '4,2 D', '5,0 R', '5,1 U', '5,4 R', '5,2 R', '5,5 U'],
    },
    { // 12
      color: 'green',
      map: ['#B.',
            '#O#',
            '#O#',
            '##B'],
      solution: ['3,2 L', '0,1 D', '3,0 U', '0,0 R', '0,1 D', '3,1 L', '3,0 U', '0,0 R', '0,1 D'],
    },
    { // 13
      color: 'orange',
      map: ['#.###.#',
            '##B#B##',
            'O##O##O',
            '##B#B##',
            '#.###.#'],
      solution: ['1,2 D', '3,2 L', '3,4 U', '1,4 L', '1,0 D', '2,2 R', '2,4 R'],
    },
    { // 14
      color: 'orange',
      map: ['#####',
            '#.#.#',
            '##O##',
            '#.#.#',
            'B#B#B'],
      solution: ['4,0 R', '4,2 U', '4,4 L', '4,2 U', '0,2 R', '0,4 D', '4,4 L', '4,2 U'],
    },
    { // 15
      color: 'orange',
      map: ['######.',
            '###.#O.',
            'B##.###',
            '#.#####',
            '#.####.',
            '.#####.',
            '#######',
            'B###.#.'],
      solution: ['2,0 R', '2,2 D', '7,0 R', '7,1 U', '5,1 R', '7,2 U', '0,2 R', '5,5 U'],
    },
    { // 16
      color: 'orange',
      map: ['.###.',
            '#####',
            'B#O#B',
            '#####',
            '.#B#.'],
      solution: ['2,0 R', '4,2 R', '4,3 U', '2,3 U', '2,4 L', '0,3 D', '2,0 R'],
    },
    { // 17
      color: 'green',
      map: ['.O.#.O.',
            '#######',
            '###.###',
            'B#####B',
            '.#####.',
            '#B#.##B',
            '#######',
            '#.O.O.#'],
      solution: ['3,0 R', '3,5 U', '3,6 L', '3,0 U', '5,1 R', '5,2 U', '1,0 R', '1,1 U', '1,2 D', '5,6 L',
                 '5,4 D'],
    },
    { // 18
      color: 'purple',
      map: ['.###O#.',
            '##...##',
            '.O###O.',
            '###O###',
            '#B###BB',
            '..#B#..'],
      solution: ['4,5 U', '4,6 L', '4,1 U', '0,1 R', '0,5 D', '4,5 L', '4,2 U', '2,2 L', '4,3 U', '5,3 U',
                 '2,3 R'],
    },
    { // 19
      color: 'purple',
      map: ['.##B##.',
            '#B###B#',
            '###O###',
            '#B###B#',
            '.##B##.'],
      solution: ['0,3 L', '1,1 R', '3,1 U', '1,1 R', '4,3 U'],
    },
    { // 20
      color: 'orange',
      map: ['#######',
            'O#####O',
            '.#B#B#.',
            '#O###O#',
            '#######',
            '#B###B#'],
      solution: ['2,2 L', '2,1 U', '2,4 R', '5,5 U', '2,5 L', '5,1 U', '2,1 U', '0,1 L', '0,0 D', '1,1 R'],
    },
    { // 21
      color: 'teal',
      map: ['##.#.##',
            '#######',
            'OB#.#BO',
            'BO###OB',
            '###.###',
            '#######'],
      solution: ['2,1 D', '3,6 L', '3,0 D', '5,1 R', '5,0 R', '5,5 U', '2,5 R', '5,6 L', '5,0 U', '0,0 R',
                 '0,1 D', '2,1 L'],
    },
  ];
});
